config/routes.rb
Rails.application.routes.draw do

   root 'welcome#home'
   get 'courses', to: 'welcome#courses'

   resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness:  case_sensitive: false }, length: {minimum: 3, maximum: 25}

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :email, presence: true, uniqueness:  case_sensitive: false }, length: { maximum: 105}, format: { with: VALID_EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :show, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def edit

  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Event was successfully created"
      redirect_to event_path(@event)
    else
      render 'new'
  end
  end

  def update

    if @event.update(event_params)
      flash[:success] = "Event was sucessfully updated"
      redirect_to event_path(@event)
    else
      render 'edit'
  end
  end

    def show

    end

  def destroy

    @event.destroy
    flash[:danger] = "Event was sucessfully deleted"
    redirect_to events_path
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end

  def courses

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= render 'shared/errors', obj: @event %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@event) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-12">
          <%= f.label :title %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of Event", autofocus: true %>
      </div>
    </div>

      <div class="form-group">
      <div class="control-label col-sm-12">
        <%= f.label :description %>
         </div>
      <div class="col-sm-8">
        <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of Event", autofocus: true %>
      </div>
    </div>


       <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10"><br/>
           <%= f.submit class: 'btn btn-primary btn-lg' %>

         </div>
    </div>


      <% end %>
<div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request and return to Events listings", events_path %> ]
    </div>

  </div>
  </div>

app/views/events/edit.html.erb
<h1 align="center">Edit existing Event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1 align="center">Listing all Events</h1>

  <% @events.each do |event| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="event-title">
        <%= link_to event.title, event_path(event) %>
      </div>
      <div class="event-body">

        <%= truncate(event.description, length: 100) %>
      </div>

      <div class="event-actions">
        <%= link_to "Edit this Event", edit_event_path(event), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete this Event", event_path(event), method: :delete, data: {confirm: "Are you sure you want to delete the Event?"}, class: "btn btn-xs btn-danger" %>

      </div>
    </div>
  </div>
</div>
<% end %>

app/views/events/new.html.erb
<h1 align="center"> Create an event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<h2 align="center">Title: <%= @event.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@event.description) %>
  <div class="event-actions">
    <%= link_to "Edit this Event", edit_event_path(@event), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete this Event", event_path(@event), method: :delete, data: {confirm: "Are you sure you want to delete the Event?"}, class: "btn btn-xs btn-danger" %>
    <%= link_to "View all Events", events_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="#">Lisa Seward</a>
      by <a href="#/">Lisa Seward</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "Courses", courses_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    
  <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Northeast College", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Courses", courses_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Login</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CollegeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>


<%= yield %>
 <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-8 col-sx-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= plualize(obj.errors.count, "error") %>
  prohibited this event from being saved:
</h2>
  <div class="panel-body">
      <ul>
      <% obj.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
          </ul>
      </div>
    </div>
  </div>
</div>
</div>
<% end %>

app/views/welcome/courses.html.erb
<h1>All Courses</h1>

<%= link_to 'Home', root_path %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
<h1>Welcome to Northeast College</h1>

  

  <%= link_to 'Sign up now', "#", class: "btn btn-danger btn-lg btn-xlarge"  %>
</div>